
BEGIN;

-- ============================================================
--  0. 기존 테이블 삭제 (CASCADE)
-- ============================================================
-- CASCADE 라서 순서는 상관없음. 과거 버전 테이블(draft_approval, category 등)도 함께 정리.
DROP TABLE IF EXISTS
    public.draft_approval,
    public.draft,
    public.notification,
    public.rag_query_ref,
    public.rag_query,
    public.user_role,
    public.role,
    public.job,
    public.history,
    public.user_sessions,
    public.doc,
    public.category,
    public.users
CASCADE;

-- ============================================================
--  [A] 기존 테이블
-- ============================================================

CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_email character varying COLLATE pg_catalog."default" NOT NULL,
    user_password character varying COLLATE pg_catalog."default" NOT NULL,
    user_name character varying COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    user_login timestamp with time zone,
    CONSTRAINT user_pkey PRIMARY KEY (user_id),
    CONSTRAINT unique_email UNIQUE (user_email)
);
COMMENT ON COLUMN public.users.user_login IS '최종로그인시간';

CREATE TABLE IF NOT EXISTS public.user_sessions
(
    session_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    session_token character varying COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    is_active boolean,
    ip_address character varying COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default", 
    CONSTRAINT user_sessions_pkey PRIMARY KEY (session_id)
);

CREATE TABLE IF NOT EXISTS public.doc
(
    doc_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    file_name character varying COLLATE pg_catalog."default",
    file_type character varying COLLATE pg_catalog."default",
    category character varying COLLATE pg_catalog."default",  -- 카테고리 (문자열로 직접 보관)
    content_full text COLLATE pg_catalog."default",   -- 원문 (PDF 추출 전체 텍스트)
    content_sum text COLLATE pg_catalog."default",    -- 요약본 (LLM 생성 / 지금은 Swagger로 채움)
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    is_deleted boolean DEFAULT false,
    user_id integer NOT NULL,
    CONSTRAINT doc_pkey PRIMARY KEY (doc_id)
);
COMMENT ON COLUMN public.doc.is_deleted IS '삭제여부';

CREATE TABLE IF NOT EXISTS public.job
(
    job_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_start timestamp without time zone,
    job_finish timestamp without time zone,
    doc_id integer,
    user_id integer,
    job_type character varying COLLATE pg_catalog."default",    -- summarize / embed / batch / document_pipeline
    job_status character varying COLLATE pg_catalog."default",  -- pending / running / success / failed / completed / cancelled

    -- ── 파이프라인 전용 컬럼 (job_type = 'document_pipeline' 에서만 사용) ──
    pipeline_stage character varying COLLATE pg_catalog."default",  -- uploaded / ocr / embedding / summarizing / completed / failed / cancelled
    progress integer DEFAULT 0,                                     -- 진행률 0~100
    is_cancelled boolean DEFAULT false,                             -- 취소 요청 플래그
    file_path character varying COLLATE pg_catalog."default",       -- 임시 업로드 파일 경로
    error_stage character varying COLLATE pg_catalog."default",     -- 실패 발생 단계
    error_message text COLLATE pg_catalog."default",                -- 실패 상세 메시지

    CONSTRAINT job_pkey PRIMARY KEY (job_id)
);
COMMENT ON TABLE public.job IS '사용자 작업이력';

-- 데이터 변경 감사 로그 (RAG 질의 로그 아님)
CREATE TABLE IF NOT EXISTS public.history
(
    history_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    change_table character varying COLLATE pg_catalog."default",
    change_text text COLLATE pg_catalog."default",
    change_time timestamp with time zone,
    CONSTRAINT history_pkey PRIMARY KEY (history_id)
);


-- ============================================================
--  [B] 추가 테이블
-- ============================================================

-- ── 권한 (멀티롤) ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.role
(
    role_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    role_name character varying COLLATE pg_catalog."default" NOT NULL,  -- 실무 담당자 / 결재권자 / 관리자
    description character varying COLLATE pg_catalog."default",
    CONSTRAINT role_pkey PRIMARY KEY (role_id),
    CONSTRAINT unique_role_name UNIQUE (role_name)
);

CREATE TABLE IF NOT EXISTS public.user_role
(
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    assigned_at timestamp with time zone DEFAULT now(),
    CONSTRAINT user_role_pkey PRIMARY KEY (user_id, role_id)
);

-- ── RAG 질의 로그 ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.rag_query
(
    query_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    query_text text COLLATE pg_catalog."default" NOT NULL,
    answer_text text COLLATE pg_catalog."default",    -- LLM 생성 답변
    source_count integer DEFAULT 0,                   -- 참고 문서 개수 (프론트 'sources: N')
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT rag_query_pkey PRIMARY KEY (query_id)
);

-- (선택) RAG 답변의 출처 문서 매핑 — 출처 추적이 필요하면 사용
CREATE TABLE IF NOT EXISTS public.rag_query_ref
(
    ref_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    query_id integer NOT NULL,
    doc_id integer,
    snippet text COLLATE pg_catalog."default",
    CONSTRAINT rag_query_ref_pkey PRIMARY KEY (ref_id)
);

-- ── 기안 / 결재 (단일 결재 → 한 테이블로 병합) ─────────────
CREATE TABLE IF NOT EXISTS public.draft
(
    draft_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    author_id integer NOT NULL,                       -- 작성자(실무 담당자)
    title character varying COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL, -- 상신 내용
    source_doc_id integer,                            -- 첨부 근거 문서(요약). 없을 수 있음
    status character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending',

    -- ▼ 결재 정보 (병합) — 대기(pending) 중엔 NULL
    approver_id integer,                              -- 결재한 사람
    reject_reason text COLLATE pg_catalog."default",  -- 반려 시에만 채움
    decided_at timestamp with time zone,              -- 결재(승인/반려) 시각
    -- ▲

    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT draft_pkey PRIMARY KEY (draft_id),
    CONSTRAINT chk_draft_status CHECK (status IN ('pending', 'approved', 'rejected','canceled', 'draft'))
);

-- ── 알림 ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.notification
(
    noti_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,                         -- 수신자
    message text COLLATE pg_catalog."default" NOT NULL,
    link character varying COLLATE pg_catalog."default",
    is_read boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT notification_pkey PRIMARY KEY (noti_id)
);


-- ============================================================
--  외래키 (기존)
-- ============================================================
ALTER TABLE IF EXISTS public.doc
    ADD CONSTRAINT fk_user_to_doc FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE IF EXISTS public.history
    ADD CONSTRAINT fk_user_history FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE IF EXISTS public.job
    ADD CONSTRAINT fk_docs_to_job FOREIGN KEY (doc_id)
    REFERENCES public.doc (doc_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE IF EXISTS public.job
    ADD CONSTRAINT fk_user_to_job FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE IF EXISTS public.user_sessions
    ADD CONSTRAINT fk_users_to_session FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

-- ============================================================
--  외래키 (추가)
-- ============================================================
ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT fk_userrole_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT fk_userrole_role FOREIGN KEY (role_id)
    REFERENCES public.role (role_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public.rag_query
    ADD CONSTRAINT fk_ragquery_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.rag_query_ref
    ADD CONSTRAINT fk_ragref_query FOREIGN KEY (query_id)
    REFERENCES public.rag_query (query_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE IF EXISTS public.rag_query_ref
    ADD CONSTRAINT fk_ragref_doc FOREIGN KEY (doc_id)
    REFERENCES public.doc (doc_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.draft
    ADD CONSTRAINT fk_draft_author FOREIGN KEY (author_id)
    REFERENCES public.users (user_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE IF EXISTS public.draft
    ADD CONSTRAINT fk_draft_sourcedoc FOREIGN KEY (source_doc_id)
    REFERENCES public.doc (doc_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE IF EXISTS public.draft
    ADD CONSTRAINT fk_draft_approver FOREIGN KEY (approver_id)
    REFERENCES public.users (user_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.notification
    ADD CONSTRAINT fk_noti_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE;


-- ============================================================
--  인덱스
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_doc_user        ON public.doc (user_id);       -- RAG 필터
CREATE INDEX IF NOT EXISTS idx_doc_category    ON public.doc (category);      -- 카테고리 필터
CREATE INDEX IF NOT EXISTS idx_job_doc         ON public.job (doc_id);
CREATE INDEX IF NOT EXISTS idx_ragquery_user   ON public.rag_query (user_id);
CREATE INDEX IF NOT EXISTS idx_draft_status    ON public.draft (status);      -- 결재 대시보드
CREATE INDEX IF NOT EXISTS idx_draft_author    ON public.draft (author_id);
CREATE INDEX IF NOT EXISTS idx_noti_user_read  ON public.notification (user_id, is_read);



COMMIT;